import {
  BookText,
  CodeXml,
  Presentation,
  SquareCheckBig,
  Youtube,
} from "lucide-react";
import { TASK_STATUSES, TASK_TYPES } from "./consts";
import type { SidebarSlide } from "./types";

export const mockSidebarSlides: SidebarSlide[] = [
  {
    id: "nsaj665bsa",
    order: "01",
    taskType: TASK_TYPES.task,
    taskName: "Командировка",
    taskStatus: TASK_STATUSES.accepted,
    taskIcon: <CodeXml />,
  },
  {
    id: "nsajbuyjsa",
    order: "02",
    taskType: TASK_TYPES.task,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.retry,
    taskIcon: <CodeXml />,
  },
  {
    id: "nsaj987bsa",
    order: "03",
    taskType: TASK_TYPES.taskHomework,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.retry,
    taskIcon: <CodeXml />,
  },
  {
    id: "nsajbsgha",
    order: "04",
    taskType: TASK_TYPES.taskHomework,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.accepted,
    taskIcon: <CodeXml />,
  },
  {
    id: "nsajbst4ea",
    order: "05",
    taskType: TASK_TYPES.taskHomework,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <CodeXml />,
  },
  {
    id: "nsaj54bsa",
    order: "06",
    taskType: TASK_TYPES.theory,
    taskName: "Круги Эйлера",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <BookText />,
  },
  {
    id: "nsa43edsa",
    order: "07",
    taskType: TASK_TYPES.theory,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <BookText />,
  },
  {
    id: "nsajbsa55",
    order: "08",
    taskType: TASK_TYPES.theory,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <BookText />,
  },
  {
    id: "nsajber4r4sa",
    order: "09",
    taskType: TASK_TYPES.test,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <SquareCheckBig />,
  },
  {
    id: "nsajb3dsa",
    order: "10",
    taskType: TASK_TYPES.test,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <SquareCheckBig />,
  },
  {
    id: "nsajbvfwsa",
    order: "11",
    taskType: TASK_TYPES.video,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <Youtube />,
  },
  {
    id: "nsaddjbsa",
    order: "12",
    taskType: TASK_TYPES.presentation,
    taskName: "Переупорядочивание массива",
    taskStatus: TASK_STATUSES.notFullfilled,
    taskIcon: <Presentation />,
  },
];
